---
language: python
python: "2.7"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
    - os: linux
      dist: xenial
      sudo: true

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - sudo pip install ansible

  # Install docker python module
  - sudo pip install docker-py

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  #1 test default container
  - ansible-playbook tests/test.yml
  - echo "SELECT 1" | curl 'http://localhost:8123/' --data-binary @-
  - docker rm -f clickhouse
  - rm -r /tmp/docker-clickhouse-*

  #2 test config changes
  - ansible-playbook tests/test-config.yml
  - "echo 'SELECT 1' | curl 'http://localhost:8124/' --data-binary @-"
  - "docker logs clickhouse 2>&1 | grep 'Starting daemon with revision 54304'"
  - "docker logs clickhouse 2>&1 | grep 'Application: Listening http://0.0.0.0:8124'"
  - "docker logs clickhouse 2>&1 | grep 'Application: Listening tcp: 0.0.0.0:9001'"
  - docker rm -f clickhouse
  - rm -r /tmp/docker-clickhouse-*


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/