---
language: python
python: "2.7"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
    - os: linux
      dist: xenial
      sudo: true
    - os: linux
      dist: precise
      sudo: true

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - sudo pip install ansible

  # Install docker python module
  - sudo pip install docker-py

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml --syntax-check
  # Full install check
  - ansible-playbook tests/test.yml -v

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/