---

- name: Start ClickHouse Server Docker container
  docker_container:
    name: "{{ clickhouse_docker_container_name }}"
    image: yandex/clickhouse-server:{{ clickhouse_docker_version }}
    state: started
    restart: "{{ clickhouse_docker_restart }}"
    network_mode: "{{ clickhouse_docker_network_mode }}"
    networks: "{{ clickhouse_docker_networks }}"
    volumes: "{{ clickhouse_docker_bind_mounts }}"
    ulimits: "{{ clickhouse_docker_ulimits }}"
    published_ports: "{{ clickhouse_docker_published_ports }}"
    exposed_ports: "{{ clickhouse_docker_exposed_ports }}"
    purge_networks: "{{ clickhouse_docker_purge_networks }}"
